name: Lint and Type Check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Run flake8
      run: |
        flake8 src/agr_curation_api tests/
    
    - name: Run mypy
      run: |
        mypy src/agr_curation_api